# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
