# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171101_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='itemNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
